title: Top Speed Auto
email: topspeedautotsa@gmail.com
phone: 780-455-6533
cell: 780-695-8333
business_address: 16718D-111 Ave NW, Edmonton, AB T5M 2S5
description: >
  An Edmonton local mechanic shop expert at fixing import vehicles, maintenance, and inspiections.
  We do tires, brakes, shocks, and light-body work.
url: "" # the base hostname & protocol for your site, e.g. http://example.com
facebook_url: "https://www.facebook.com/topspeedautoedmonton/"
instagram_url: "https://www.instagram.com/explore/locations/1723186284586354/top-speed-auto/"
