name: Production deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: jekyll build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    - name: jekyll build
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
    - uses: actions/upload-artifact@v2
      with:
        name: site
        path: _site/

  deploy:
    name: deploy ftp
    runs-on: ubuntu-latest
    needs: build
    steps:

    - uses: actions/download-artifact@v2.0.5
      with:
        name: site
        path: _site

    - uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: "_site"